export const PetVaccines: string[] = [
  'V8',
  'V10',
  'V11',
  'Antirrábica',
  'Giardíase',
  'Leptospirose',
  'Giárdia',
  'Raiva',
  'FIV',
  'Felv',
  'Coronavirose',
  'Parvovírus',
  'Cinomose',
  'Adenovírus Tipo 2',
  'Tosse dos Canis',
  'Calicivirose',
  'Panleucopenia Felina',
  'Clamidiose',
  'Leucemia Felina',
  'Gripe Equina',
  'Influenza Equina',
  'Rinopneumonite Equina',
  'Febre do Nilo Ocidental',
  'Anemia Infecciosa Equina',
  'Tétano',
];
